// Bundler entrypoint (webpack / rollup / esbuild / vite). The
// `bundler`-target wasm-bindgen build uses ESM import of `.wasm` and
// relies on the bundler to resolve it — no runtime `init` call.

// Relative-path import (not `#wasm/...`) so the compiled JS resolves
// identically in raw browsers and bundlers alike. Bundlers still
// handle the trailing `.wasm` import inside the wasm-bindgen glue —
// that's what `--target bundler` was built for.
// @ts-expect-error — file generated by scripts/build-wasm.mjs
import * as wasm from "../wasm/bundler/ktav.js";

import { ktavMessageError, toKtavError } from "./internal/api.js";
import type { KtavInput, KtavValue } from "./internal/api.js";
export type { KtavArray, KtavErrorEnvelope, KtavInput, KtavObject, KtavValue, Ktav } from "./internal/api.js";
export { KtavError, ktavMessageError, toKtavError } from "./internal/api.js";

export function loads<T = KtavValue>(s: string): T {
    try {
        return wasm.loads(s) as T;
    } catch (e) {
        throw toKtavError(e);
    }
}

export function loadsStrict<T = KtavValue>(s: string): T {
    try {
        return wasm.loadsStrict(s) as T;
    } catch (e) {
        throw toKtavError(e);
    }
}

export function dumps<T extends KtavInput = KtavInput>(obj: T): string {
    if (obj === null || typeof obj !== "object") {
        throw ktavMessageError("top-level Ktav document must be an object or array");
    }
    try {
        return wasm.dumps(obj);
    } catch (e) {
        throw toKtavError(e);
    }
}

export function stringifyForceStrings<T extends KtavInput = KtavInput>(obj: T): string {
    if (obj === null || typeof obj !== "object") {
        throw ktavMessageError("top-level Ktav document must be an object or array");
    }
    try {
        return wasm.stringifyForceStrings(obj);
    } catch (e) {
        throw toKtavError(e);
    }
}

export function format(s: string): string {
    try {
        return wasm.format(s);
    } catch (e) {
        throw toKtavError(e);
    }
}

export function emitCanonical<T extends KtavInput = KtavInput>(obj: T): string {
    if (obj === null || typeof obj !== "object") {
        throw ktavMessageError("top-level Ktav document must be an object or array");
    }
    try {
        return wasm.emitCanonical(obj);
    } catch (e) {
        throw toKtavError(e);
    }
}

export function canonicalFromSource(s: string): string {
    try {
        return wasm.canonicalFromSource(s);
    } catch (e) {
        throw toKtavError(e);
    }
}
