// Bundler entrypoint (webpack / rollup / esbuild / vite). The
// `bundler`-target wasm-bindgen build uses ESM import of `.wasm` and
// relies on the bundler to resolve it — no runtime `init` call.

// Relative-path import (not `#wasm/...`) so the compiled JS resolves
// identically in raw browsers and bundlers alike. Bundlers still
// handle the trailing `.wasm` import inside the wasm-bindgen glue —
// that's what `--target bundler` was built for.
// @ts-expect-error — file generated by scripts/build-wasm.mjs
import * as wasm from "../wasm/bundler/ktav.js";

import type { KtavInput, KtavValue } from "./api.js";
export type { KtavArray, KtavError, KtavInput, KtavObject, KtavValue, Ktav } from "./api.js";

export function loads<T = KtavValue>(s: string): T {
    return wasm.loads(s) as T;
}

export function loadsStrict<T = KtavValue>(s: string): T {
    return wasm.loadsStrict(s) as T;
}

export function dumps<T extends KtavInput = KtavInput>(obj: T): string {
    return wasm.dumps(obj);
}

export function stringifyForceStrings<T extends KtavInput = KtavInput>(obj: T): string {
    return wasm.stringifyForceStrings(obj);
}
